### ISSUE TITLE
Taskbar icon after pinning the program reverts to default ConEmu icon. Systray icon is always ConEmu's.

### ISSUE THREAD

**Issue by dcominottim** [cmderdev/cmder#154]
First of all, congratulations on your great customization and integration work! Cmder is a true visual joy. :-) As for the report, the issue can be easily reproduced just by 1) launching Cmder, right-clicking its icon on the taskbar, and choosing "Pin this program...", and 2) looking also at the systray icons.

**Comment by RDeluxe** [comment]
Well, sadly @ClementParis016's solution does not work for me. Everything was working perfectly well, but I missclicked an unpinned cmder. Since then, impossible to pin it down corretly.
My cmder is my dropbox folder (portability ftw), and when I pin it from the explorer (without launching it first) I got this :
![2015-01-15_17-28-39](https://cloud.githubusercontent.com/assets/2767681/5761512/305fa246-9cdc-11e4-9d16-15019d947da9.png)

**Comment by kohenkatz** [comment]
@RDeluxe Check if you have the "Special Folder Name" problem that I had [above](https://github.com/bliker/cmder/issues/154#issuecomment-53323677).

**Comment by RDeluxe** [comment]
@kohenkatz Using taksbar inspector it seems that I have the same problem. I tried your solution (unpinning from start screen, pinning again on taskbar) but without luck.
![2015-01-15_19-19-48](https://cloud.githubusercontent.com/assets/2767681/5763536/89521a96-9ceb-11e4-8405-c36661d78269.png)

It launches the correct program, so the problem is coming from the shortcut.

**Comment by Bujutsu** [comment]
For a temporary workaround I've done this:
* Created a shortcut to *c:\tools\cmder\Cmder.exe* on Desktop
* Opened from there
* Pinned the running application

It works even if you delete the shortcut.

**Comment by MartiUK** [comment]
@Bujutsu This is how I've always done it.

**Comment by RDeluxe** [comment]
This is working, thanks @Bujutsu .

**Comment by DoCode** [comment]
@Bujutsu No, this ends with this icon
![image](https://cloud.githubusercontent.com/assets/1489133/6115942/94dda96c-b0a9-11e4-9f07-c9fa26500c4c.png)

**Comment by RDeluxe** [comment]
@DoCode After fighting with this issue for a long time,  @Bujutsu method is working for me. Did you launch the application then pinned, and not drag and drop the shortcut to the taskbar ?

I tried to clean the folder containing the taskbar data. And I also cleaned the registry key. These actions did not solve my problem however, I was becoming desesperate ^^'.

**Comment by DoCode** [comment]
Yes, i followed the three steps above...
No Resolution. Always show the ConEmu's one...

**Comment by RDeluxe** [comment]
Just to be sure (I actually don't think it could have an impact, but seeing how windows manages its shortcuts ...), you created the desktop shortcut manually (without a drag and drop) ?

**Comment by DoCode** [comment]
![image](https://cloud.githubusercontent.com/assets/1489133/6116679/016f11ce-b0af-11e4-8074-cc4c45ea7e50.png)
![image](https://cloud.githubusercontent.com/assets/1489133/6116688/0aa8aef8-b0af-11e4-90f7-5faa31cf6b35.png)
![image](https://cloud.githubusercontent.com/assets/1489133/6116690/0ef40d5e-b0af-11e4-8f57-542d9e9725c9.png)
![image](https://cloud.githubusercontent.com/assets/1489133/6116691/12ca6f9a-b0af-11e4-9283-4356a3282f2d.png)
![image](https://cloud.githubusercontent.com/assets/1489133/6116699/18047a8c-b0af-11e4-9359-aa311e1ec5f0.png)

**Comment by RDeluxe** [comment]
Well, that's actually how I think it can fail. I'm wondering if the 'create shortcut' is not creating an App ID (GUID?).
Try with right clicking on your desktop background, and create a shortcut from there (new -> Shortcut)

**Comment by DoCode** [comment]
Ohmy...

![09-02-_2015_23-03-54_1_1](https://cloud.githubusercontent.com/assets/1489133/6116853/5b3bcb56-b0b0-11e4-8dca-7be154563327.gif)

**Comment by RDeluxe** [comment]
Well, you can try to check the App id/path to see if a strange GUID appear using http://rammichael.com/7-taskbar-tweaker.
There seems to be a whole lot of different problems (changing icon, dual icons, etc). I guess there is something that could be done on cmder side to solve that, but I'm not a windows expert by any means

**Comment by DoCode** [comment]
Now... The behavior comes from the missing icons folder in cmder_mini.zip.
Related to issue #373.

**Comment by austinwagner** [comment]
@RDeluxe Unfortunately the problem lies in the fact that it's not possible to get the App ID through the Windows API unless it has been explicitly set by the application. Windows seems to generate different App IDs depending on how the shortcut is created. I believe the only way to get the generated App ID would be to do what Taskbar Tweaker does and hook into Explorer.

**Comment by PierreDuplouy** [comment]
@Bujutsu thanks, that did the trick.

**Comment by ittayd** [comment]
I'm using 1.1.4.1.  @Bujutsu's method doesn't work for me. When cmder launches (from shortcut or directly from the exe), the icon is ConEmu's. Pinning the running application will launch ConEmu. Dragging the shortcut/exe to the task bar will show the cmder icon but the launch ConEmu. Also, in the task manager, I see the process name ConEmu.exe (running ConEmuC64.exe).

**Comment by mikesigs** [comment]
I fixed this by right clicking on the taskbar icon, then right clicking on ConEmu and opening the Properties. Then I changed the Target to `<path to cmder>\Cmder.exe` and Start in: to `<path to cmder>`. I had to kill and restart the Explorer.exe process and it started showing the Cmder icon again, as well as launching Cmder without creating a second taskbar icon.

**Comment by nogwater** [comment]
I had problems on both Windows 7 and 8.1.  The way I finally got it working was by doing a fresh extract to C:\cmder\, then I *dragged* the Cmder.exe to my taskbar and dropped it there.  Based on the success rates of other solutions, I don't know if this'll work for anyone else, but hopefully it will.  Good luck!

**Comment by RDeluxe** [comment]
@mikesigs solution worked for me (I unpinned cmder by mistake).

**Comment by glucas** [comment]
+1, @mikesigs solution worked for me on Win 8.1.

**Comment by Sigmanor** [comment]
Also you can just create shortcut on desktop, and pin it in taskbar.

**Comment by ittayd** [comment]
None of these methods work for me

**Comment by Sigmanor** [comment]
@ittayd then you maybe do something wrong, @mikesigs solution works perfect. Creating shortcut on desktop and pin it in taskbar works too.

**Comment by ksubileau** [comment]
I fixed this issue when I decided to move the Cmder folder from C:\Program Files to D:\App.

**Comment by ittayd** [comment]
I don't think I can go very wrong with something like creating a desktop
shortcut and pinning it...

**Comment by ittayd** [comment]
Yeah, that solved it for me (moving cmder folder directly under c:). Kind
of ugly though...

**Comment by mikesigs** [comment]
@ittayd If you use a tool like Chocolatey to install Cmder, it puts it under c:\bin\cmder. It's a bit odd for Windows, but being that it's not an installed app, but a portable app, it makes more sense for it to go somewhere other than C:\Program Files imho.

**Comment by arthurspa** [comment]
@jacobch, your solution works!! I'm using Windows 8.1 64 bits. 

=)

**Comment by RDugan23** [comment]
@Stanzilla Why was this closed? It's still an issue. Non of the above worked for me. I'm on Window 10

**Comment by Stanzilla** [comment]
@RDugan23 I tested it on Win10 and it works. You have to right click cmder.exe in the cmder folder and pin it. then works fine, stays as one (the correct) icon. This is was with the development branch code. If you want to test a build, get this one https://github.com/Stanzilla/cmder/releases/tag/1.2.6

**Comment by RDugan23** [comment]
@Stanzilla Thank you for your help. Using your build I was able to get it working. One change I had to make, though, was with the vendor/init.bat file. Using the bat file that came with your build the 'ls' command wouldn't work. I had to revert that file back to my old version and the 'ls' command began working again. Let me know if you want more info. Again, thank you for all of your hard work and your help! :)

**Comment by hmny** [comment]
still have the same problem that mentioned by other people on Windows 10.

**Comment by Stanzilla** [comment]
@hmny what exactly? did you try it the way I mentioned and with the version I mentioned?
@RDugan23  what exactly did you have to change?

**Comment by RDugan23** [comment]
@Stanzilla Somehow I messed things up so I did a fresh install with you latest build and everything seems to be working now. I don't know what I did wrong last time. Thanks again for your help.

**Comment by Stanzilla** [comment]
Sounds great :)

**Comment by winston01** [comment]
How will this work in the new release, where - as I can see - there is no cmder.exe, but Cmder.bat which launches ConEmu.exe, and I don't see a way of that not appearing as a separate icon on the task bar. Does anyone have a solution?

**Comment by winston01** [comment]
Sorry, I just saw this was closed. Anyway, the question is still valid.

**Comment by kohenkatz** [comment]
@winston01 I'm not sure where you got the idea that the new release has no `cmder.exe`. The source files of the executable still exist in the Git repository, just not a built version of the executable.  If you check out the code from Git instead of downloading the release zip files, you will have to build the executable yourself.

**Comment by winston01** [comment]
@kohenkatz I was testing the development branch and that one does not compile the executable.

**Comment by kohenkatz** [comment]
@winston01 you have to compile the executable yourself when you are on the development branch.  Look in the `launcher` folder in the source for the code.

**Comment by winston01** [comment]
@kohenkatz Thx for you help, I have the Cmder.exe now!

**Comment by liulios** [comment]
Sadly none of the above worked for me too, on Windows 10 x64, but I figure out one myself.
* Run cmder.exe.
* Pin the running program.
* Right click on the pinned taskbar icon, then right click on the program name (should be "Console Emulator (x86)"), select "Property".
* In the Property window, you may see that the target is "xxx\cmder\vendor\conemu-maximus5\ConEmu.exe". Change it into "xxx\cmder\Cmder.exe".
* Done!

**Comment by ksubileau** [comment]
@liulios This works for me too on Windows 10, but this has already been said by @mikesigs <a href="https://github.com/cmderdev/cmder/issues/154#issuecomment-99610369">here</a> ;)

**Comment by liulios** [comment]
@ksubileau Oops! I missed it :)

**Comment by Frankusky** [comment]
Sorry for bump this, but the issue still alive (also the right click menu on the task bar doesnt appears) on windows 7 64bits. I was able to fix this using @nogwater [fix](https://github.com/cmderdev/cmder/issues/154#issuecomment-100383734)

**Comment by mikesigs** [comment]
I found another fix for this. Right-click Cmder.exe and then Pin to Start. Then find it in the Start Menu and right-click it and Pin to Taskbar.

**Comment by im-zablon** [comment]
@mikesigs thank you so very much. Your 'fix' worked wonderfully.

**Comment by sixpetrov** [comment]
You can also create shortcut on the desktop and then "Pin to taskbar"

**Comment by ryan-z** [comment]
The above tricks do not work if there is no running cmder instance and launching "cmd" from the run dialog (cmder is my default terminal)

**Comment by PlugaruT** [comment]
This issue is still present on Windows 10

**Comment by paulviks0x30** [comment]
On Windows 10 Pro I just right click on cmder.exe and choose pin to taskbar. Just it! Now work like a charm :-)

**Comment by lawweiliang** [comment]
Solution.
1) Right click the Cmder.exe to 'pin to start'
2) Then, run Cmder.exe
3) Then, 'pin to taskbar'

**Comment by ZodmanPerth** [comment]
> 1. Right click the Cmder.exe to 'pin to start'
> 1. Then, run Cmder.exe
> 1. Then, 'pin to taskbar'

Before you do this, make sure you've deleted any previous "pin to start" shortcut:

1. Open run dialog and run `shell:startup`
2. Navigate up one folder (to `Programs`)
3. Delete any `Cmder` shortcut there

Now if you follow the steps from @lawweiliang it works.
(Tested on Windows 11)
